apiVersion: v1
kind: Service
metadata:
  name: nexus-column-prune-service
  namespace: nexus
  labels:
    app: nexus-column-prune
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
  selector:
    app: nexus-column-prune
