apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-column-prune-deploy
  namespace: nexus1
  labels:
    app: nexus-column-prune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus-column-prune
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nexus-column-prune
    spec:
      containers:
        - name: nexus-column-prune
          image: trahulprabhu38/column-pruning:v1-linux
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources: {}
