apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-column-prune-deploy
  namespace: nexus
  labels:
    type: column-prune-deployment
    app: nexus-project
spec:
  replicas: 3
  selector:
    matchLabels:
      type: column-prune-pod
      app: nexus-column-prone-project      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        type: pod
        app: nexus-column-prone-project        
    spec:
      containers:
        - name: nexus-frontend
          image: trahulprabhu38/column-pruning:v1-linux                    
          imagePullPolicy: Always 
          ports:
            - containerPort: 8501
          resources: {}




    
  