apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-frontend-deploy
  namespace: nexus
  labels:
    type: frontend-deployment
    app: nexus-project
spec:
  replicas: 3
  selector:
    matchLabels:
      type: pod
      app: nexus-frontend-project
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        type: pod
        app: nexus-frontend-project      
    spec:
      containers:
        - name: nexus-frontend
          image: trahulprabhu38/nexus-frontend:v1-linux
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
          resources: {}



