apiVersion: v1
kind: Service
metadata:
  name: intent-agent
  namespace: nexus1
  labels:
    app: intent-agent

spec:
  type: NodePort 
  selector:
    app: intent-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
