apiVersion: v1
kind: Secret
metadata:
  name: sql-validator-secrets
  namespace: nexus
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n 'your-value' | base64
  # user -> dXNlcg==
  # password -> cGFzc3dvcmQ=
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: YWNhZGVtaWNfZGI=
