apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    type: service
    app:  nexus-project
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
      type: pod
      app: nexus-project        


