# ---
# # PostgreSQL Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
#   namespace: nexus1
#   labels:
#     app: postgres
# spec:
#   type: ClusterIP
#   ports:
#   - port: 5432
#     targetPort: 5432
#     protocol: TCP
#     name: postgres
#   selector:
#     app: postgres

# ---
# # SQL Validator API Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: sql-validator-api-service
#   namespace: nexus1
#   labels:
#     app: sql-validator-api
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 8000
#     targetPort: 8000
#     protocol: TCP
#     name: http
#   selector:
#     app: sql-validator-api

